SELECT * FROM MEMBER
INSERT INTO MEMBER  (ID, PWD, NICKNAME, PHONE, AUTH)  
VALUES('5', '5', '55', '55', 0) 

DROP TABLE MEMBER
CASCADE CONSTRAINTS;

CREATE TABLE MEMBER(
	ID VARCHAR2(50) PRIMARY KEY,
	PWD VARCHAR2(50) NOT NULL,
	NICKNAME VARCHAR2(50) NOT NULL,
	PHONE VARCHAR2(50) UNIQUE,
	AUTH NUMBER(1) NOT NULL
);

