DROP TABLE MEMBER
CASCADE CONSTRAINTS;

CREATE TABLE Member(
	ID VARCHAR2(50) PRIMARY KEY,
	PWD VARCHAR2(50) NOT NULL,
	NICKNAME VARCHAR2(50) NOT NULL,
	PHONE VARCHAR2(50) NOT NULL,
	POINT NUMBER(10) NOT NULL,
	MONEY NUMBER(10) NOT NULL,
	AUTH NUMBER(2) NOT NULL
);

INSERT INTO MEMBER
VALUES('1', '1', '윤상필', '폰번호', 50000, 50000, 0)

SELECT * FROM MEMBEr

 UPDATE MEMBER  
 SET point = 50000 
 WHERE ID = '5' 
  UPDATE MEMBER  SET point = 50000  WHERE ID = '1' 